# numpy 100 문제

In [1]:
#1번

import numpy as np

In [2]:
#2번
np.__version__

'1.19.2'

In [5]:
#3번

z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
#4번
z.size

10

In [ ]:
#5번

In [12]:
#6번
s = np.zeros(10)
s[4] = 1
print(s)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
#7

a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [21]:
#8

a = np.arange(50)
a[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [26]:
#9

a = np.arange(9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
#10
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [35]:
#11
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
#12

np.random.random((3,3,3))

array([[[0.29790827, 0.271961  , 0.33995504],
        [0.06062443, 0.7166638 , 0.23747448],
        [0.5073151 , 0.01408775, 0.38434842]],

       [[0.07462496, 0.11286913, 0.35784656],
        [0.60159838, 0.14913128, 0.75403173],
        [0.82662991, 0.96445623, 0.58440409]],

       [[0.05392612, 0.37471937, 0.83911415],
        [0.45806159, 0.93394795, 0.71181796],
        [0.41847559, 0.62909895, 0.77072433]]])

In [42]:
#13
a = np.random.random((10,10))
print(a.max())
print(a.min())

0.9944976227099778
0.005989137707296366


In [45]:
#14

np.random.random(30).mean()

0.6058263288667214

In [47]:
#15
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [51]:
#16
z = np.ones((5,5))
z = np.pad(z, pad_width = 1, mode = 'constant', constant_values = 0)
z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [55]:
z = np.ones((5,5))
z[:,[0,-1]] = 0
z[1:-1,1:-1] = 1
z

array([[0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.]])

In [62]:
#17

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [66]:
#18번
x = np.arange(4)
z = np.diag(1+x,k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [75]:
#19번

z = np.zeros((8,8), dtype = int)
z[1::2,::2] = 1
z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [79]:
#20번
np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [82]:
#21번

z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [86]:
#22번
z = np.random.random((5,5))
z = (z - np.mean(z) / np.std(z))
print(z)

[[-1.32305614 -0.82797537 -1.40957007 -1.37195965 -0.91183751]
 [-0.97908398 -1.29765178 -0.57237446 -1.01510765 -0.68530837]
 [-0.60161813 -1.30693536 -1.05253803 -1.22129499 -0.63798306]
 [-0.69706219 -0.91269754 -1.14734438 -0.72396521 -1.4134812 ]
 [-1.45275519 -0.53791389 -0.55881165 -1.44783143 -0.77159356]]


In [87]:
#23번


color = np.dtype([("r",np.ubyte,1),
                 ("g",np.ubyte,1),
                 ("b",np.ubyte,1),
                 ("a",np.ubyte,1)])


<ipython-input-87-877bc82ebd50>:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r",np.ubyte,1),


In [88]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [91]:
#24
a = np.ones((5,3))
b = np.ones((3,2))
np.dot(a,b)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [92]:
a @ b

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [94]:
#25
z = np.arange(11)
z[(3<z) & (z <8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [95]:
#26

print(sum(range(5),-1))

9


In [105]:
sum(range(5),-1)


9

In [106]:
#27

ValueError: Integers to negative integer powers are not allowed.

In [116]:
#28
np.array(0) / np.array(0)
np.array(0) // np,array(0)
np.array(np.array([np.nan])).astype(int).astype(float)

<ipython-input-116-bc6903bb9407>:2: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


TypeError: unsupported operand type(s) for //: 'int' and 'module'

In [117]:
import seaborn as sns

In [120]:
df = sns.load_dataset('tips')

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [122]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [123]:
df.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [147]:
a = df['smoker'] == "No"
b = df['sex'] == "Male"
b

0      False
1       True
2       True
3       True
4      False
       ...  
239     True
240    False
241     True
242     True
243    False
Name: sex, Length: 244, dtype: bool

In [149]:
df2 = df[a&b]

In [151]:
df2['sex'].unique()
df2['smoker'].unique()

['No']
Categories (1, object): ['No']

In [155]:
import pandas as pd
df1 = pd.DataFrame({"고객번호" : [1001,1002,1003,1004,1005,1006,1007],
                  "이름" : ['강감찬','홍길동','이순신','장보고','유관순','신사임당',
                          '세종대왕']},
                  columns=['고객번호','이름'])

In [157]:
df2 = pd.DataFrame({"고객번호" : [1001,1001, 1005, 1006, 1008, 1001],
                   '금액' : [10000,20000,15000,5000,10000,30000]}
                  ,columns=['고객번호','금액'])

In [158]:
df2

고객번호     금액
0  1001  10000
1  1001  20000
2  1005  15000
3  1006   5000
4  1008  10000
5  1001  30000

In [159]:
pd.merge(df1,df2)

고객번호    이름     금액
0  1001   강감찬  10000
1  1001   강감찬  20000
2  1001   강감찬  30000
3  1005   유관순  15000
4  1006  신사임당   5000