In [1]:
from Preprocess import *

PATH =  './data_in/data/ChatbotData.csv'
VOCAB_PATH = 'data_in/data/vocabulary.txt'

inputs, outputs = load_data(PATH) #question, answer
char2idx, idx2char, vocab_size = load_vocabulary(PATH, VOCAB_PATH,
                                                tokenize_as_morph = False) 
#단어사전 만들기
#False 로 했으니 띄어쓰기 단위로, 형태소 단위가 아니라


index_inputs, input_seq_len = enc_processing(inputs, char2idx, tokenize_as_morph = False) #encoder 입력값 단어id 시퀀스화 하기
index_outputs, output_seq_len = dec_output_processing(outputs, char2idx,
                                                     tokenize_as_morph = False) #디코더 입력값 단어 id 시퀀스화 하기

index_targets = dec_target_processing(outputs, char2idx,
                                     tokenize_as_morph = False) #디코더 타겟값 단어 id 시퀀스화 하기



In [2]:
index_inputs

array([[12418, 14766,     0, ...,     0,     0,     0],
       [10984,  8477,  9293, ...,     0,     0,     0],
       [13566,  1337, 16266, ...,     0,     0,     0],
       ...,
       [16194, 15231,  4757, ...,     0,     0,     0],
       [ 1623,  2031,  1800, ...,     0,     0,     0],
       [ 2448, 10642,     0, ...,     0,     0,     0]])

In [3]:
index_outputs

array([[    1, 12088,  7598, ...,     0,     0,     0],
       [    1,  8181, 10565, ...,     0,     0,     0],
       [    1,  1727,   388, ...,     0,     0,     0],
       ...,
       [    1,  3622,     0, ...,     0,     0,     0],
       [    1, 13057, 12962, ...,     0,     0,     0],
       [    1,  5038, 14237, ...,     0,     0,     0]])

In [4]:
index_targets

array([[12088,  7598,  1591, ...,     0,     0,     0],
       [ 8181, 10565,     2, ...,     0,     0,     0],
       [ 1727,   388,  8217, ...,     0,     0,     0],
       ...,
       [ 3622,     2,     0, ...,     0,     0,     0],
       [13057, 12962,  3982, ...,     0,     0,     0],
       [ 5038, 14237, 19434, ...,     0,     0,     0]])

In [7]:
data_configs = {}
data_configs['char2idx'] = char2idx
data_configs['idx2char'] = idx2char
data_configs['vocab_size'] = vocab_size
data_configs['pad_symbol'] = PAD
data_configs['std_symbol'] = STD
data_configs['end_symbol'] = END
data_configs['unk_symbol'] = UNK



In [13]:
DATA_IN_PATH = './data_in/'
TRAIN_INPUTS = 'train_inputs.npy'
TRAIN_OUTPUTS = 'train_outputs.npy'
TRAIN_TARGETS = 'train_targets.npy'
DATA_CONFIGS = 'data_configs.json'


np.save(open(DATA_IN_PATH + TRAIN_INPUTS, 'wb'), index_inputs)
np.save(open(DATA_IN_PATH + TRAIN_OUTPUTS, 'wb'), index_outputs)
np.save(open(DATA_IN_PATH + TRAIN_TARGETS, 'wb'), index_targets)

json.dump(data_configs, open(DATA_IN_PATH + DATA_CONFIGS, 'w'))